require("core.plugin-config.nvim-tree")
require("core.plugin-config.telescope")
require("core.plugin-config.lsp-config")
require("core.plugin-config.tree-sitter")
require("core.plugin-config.completions")
require("core.plugin-config.moonfly")
require("core.plugin-config.devicons")
